// Local image lookup for the product catalog, keyed by SKU family.
// Photos stay local static files (public/images/products/) - only the
// catalog data itself (name, price, availability, variants) comes from
// Supabase. Generated from image-manifest.csv; regenerate this file if
// the organized photo set changes.
export const productImages = {
  "APP-001": { image: "/images/products/apparel/APP-001-teal-life.png", lifeImage: null },
  "APP-002": { image: "/images/products/apparel/APP-002-sand-life.png", lifeImage: null },
  "APP-003": { image: "/images/products/apparel/APP-003-navy-studio.png", lifeImage: "/images/products/apparel/APP-003-navy-life.png" },
  "APP-004": { image: "/images/products/apparel/APP-004-aqua-studio.png", lifeImage: "/images/products/apparel/APP-004-aqua-life.png" },
  "APP-005": { image: "/images/products/apparel/APP-005-black-studio.png", lifeImage: "/images/products/apparel/APP-005-black-life.png" },
  "APP-006": { image: "/images/products/apparel/APP-006-black-studio.png", lifeImage: "/images/products/apparel/APP-006-black-life.png" },
  "APP-007": { image: "/images/products/apparel/APP-007-tropical-life.png", lifeImage: null },
  "BCH-001": { image: "/images/products/beach-essentials/BCH-001-studio.png", lifeImage: "/images/products/beach-essentials/BCH-001-life.png" },
  "BCH-002": { image: "/images/products/beach-essentials/BCH-002-studio.png", lifeImage: "/images/products/beach-essentials/BCH-002-life.png" },
  "BCH-003": { image: "/images/products/beach-essentials/BCH-003-palm-print-studio.png", lifeImage: "/images/products/beach-essentials/BCH-003-life.png" },
  "BCH-004": { image: "/images/products/beach-essentials/BCH-004-black-studio.png", lifeImage: "/images/products/beach-essentials/BCH-004-life.png" },
  "BCH-005": { image: "/images/products/beach-essentials/BCH-005-studio.png", lifeImage: "/images/products/beach-essentials/BCH-005-life.png" },
  "BCH-006": { image: "/images/products/beach-essentials/BCH-006-studio.png", lifeImage: "/images/products/beach-essentials/BCH-006-life.png" },
  "BCH-007": { image: "/images/products/beach-essentials/BCH-007-studio.png", lifeImage: "/images/products/beach-essentials/BCH-007-life.png" },
  "BCH-008": { image: "/images/products/beach-essentials/BCH-008-studio.png", lifeImage: "/images/products/beach-essentials/BCH-008-life.png" },
  "BCH-009": { image: "/images/products/beach-essentials/BCH-009-aviator-black-life.png", lifeImage: null },
  "BCH-010": { image: "/images/products/beach-essentials/BCH-010-studio.png", lifeImage: "/images/products/beach-essentials/BCH-010-life.png" },
  "BCH-011": { image: "/images/products/beach-essentials/BCH-011-aqua-life.png", lifeImage: null },
  "BCH-012": { image: "/images/products/beach-essentials/BCH-012-blue-studio.png", lifeImage: "/images/products/beach-essentials/BCH-012-blue-life.png" },
  "FIN-001": { image: "/images/products/snorkel-dive/FIN-001-black-studio.png", lifeImage: "/images/products/snorkel-dive/FIN-001-black-life.png" },
  "FIN-002": { image: "/images/products/snorkel-dive/FIN-002-black-studio.png", lifeImage: "/images/products/snorkel-dive/FIN-002-black-life.png" },
  "FIN-003": { image: "/images/products/snorkel-dive/FIN-003-aqua-studio.png", lifeImage: "/images/products/snorkel-dive/FIN-003-aqua-life.png" },
  "FSH-001": { image: "/images/products/fishing/FSH-001-studio.png", lifeImage: "/images/products/fishing/FSH-001-life.png" },
  "FSH-002": { image: "/images/products/fishing/FSH-002-studio.png", lifeImage: "/images/products/fishing/FSH-002-life.png" },
  "FSH-003": { image: "/images/products/fishing/FSH-003-studio.png", lifeImage: "/images/products/fishing/FSH-003-life.png" },
  "FSH-004": { image: "/images/products/fishing/FSH-004-studio.png", lifeImage: "/images/products/fishing/FSH-004-life.png" },
  "FSH-005": { image: "/images/products/fishing/FSH-005-studio.png", lifeImage: "/images/products/fishing/FSH-005-life.png" },
  "FSH-006": { image: "/images/products/fishing/FSH-006-studio.png", lifeImage: "/images/products/fishing/FSH-006-life.png" },
  "FSH-007": { image: "/images/products/fishing/FSH-007-studio.png", lifeImage: "/images/products/fishing/FSH-007-life.png" },
  "FSH-008": { image: "/images/products/fishing/FSH-008-studio.png", lifeImage: "/images/products/fishing/FSH-008-life.png" },
  "KIT-001": { image: "/images/products/surfing/KIT-001-blue-studio.png", lifeImage: "/images/products/surfing/KIT-001-blue-life.png" },
  "KIT-002": { image: "/images/products/surfing/KIT-002-black-studio.png", lifeImage: "/images/products/surfing/KIT-002-black-life.png" },
  "SNK-001": { image: "/images/products/snorkel-dive/SNK-001-black-studio.png", lifeImage: "/images/products/snorkel-dive/SNK-001-black-life.png" },
  "SNK-002": { image: "/images/products/snorkel-dive/SNK-002-black-studio.png", lifeImage: "/images/products/snorkel-dive/SNK-002-black-life.png" },
  "SNK-003": { image: "/images/products/snorkel-dive/SNK-003-aqua-studio.png", lifeImage: "/images/products/snorkel-dive/SNK-003-aqua-life.png" },
  "SNK-004": { image: "/images/products/snorkel-dive/SNK-004-black-studio.png", lifeImage: "/images/products/snorkel-dive/SNK-004-black-life.png" },
  "SNK-005": { image: "/images/products/snorkel-dive/SNK-005-studio.png", lifeImage: "/images/products/snorkel-dive/SNK-005-life.png" },
  "SUR-001": { image: "/images/products/surfing/SUR-001-studio.png", lifeImage: "/images/products/surfing/SUR-001-life.png" },
  "SUR-002": { image: "/images/products/surfing/SUR-002-studio.png", lifeImage: "/images/products/surfing/SUR-002-life.png" },
  "SUR-003": { image: "/images/products/surfing/SUR-003-blue-studio.png", lifeImage: "/images/products/surfing/SUR-003-blue-life.png" },
  "SUR-004": { image: "/images/products/surfing/SUR-004-black-studio.png", lifeImage: "/images/products/surfing/SUR-004-black-life.png" },
  "SUR-005": { image: "/images/products/surfing/SUR-005-studio.png", lifeImage: "/images/products/surfing/SUR-005-life.png" },
  "SUR-006": { image: "/images/products/surfing/SUR-006-tropical-studio.png", lifeImage: "/images/products/surfing/SUR-006-tropical-life.png" },
  "WET-001": { image: "/images/products/snorkel-dive/WET-001-black-life.png", lifeImage: null },
  "WET-002": { image: "/images/products/apparel/WET-002-coral-life.png", lifeImage: null },
};
