// Product catalog data extracted from The_Rusti_Shack_Dataset.xlsx (Products tab).
// One entry per product family (sizes/colors collapsed) - matches the organized
// photo set in public/images/products/. Treat the source spreadsheet as the
// source of truth until there is a real backend (see CLAUDE.md).
export const products = [
  {
    sku: "APP-002",
    name: "Apo Island Souvenir Tee",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Shirts",
    price: 26.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/APP-002-sand-life.png",
  },
  {
    sku: "APP-004",
    name: "Bikini Set \u2014 Womens",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Swimwear",
    price: 54.0,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/APP-004-aqua-studio.png",
  },
  {
    sku: "APP-003",
    name: "Boardshorts \u2014 Mens",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Bottoms",
    price: 44.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/APP-003-navy-studio.png",
  },
  {
    sku: "APP-007",
    name: "Flip Flops Tropical",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Footwear",
    price: 14.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/APP-007-tropical-life.png",
  },
  {
    sku: "APP-005",
    name: "One-Piece Swimsuit",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Swimwear",
    price: 58.0,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/APP-005-black-studio.png",
  },
  {
    sku: "WET-002",
    name: "Rashguard Long Sleeve",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Rashguards",
    price: 32.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/WET-002-coral-life.png",
  },
  {
    sku: "APP-001",
    name: "Tide & Tempo Logo Tee",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Shirts",
    price: 24.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/APP-001-teal-life.png",
  },
  {
    sku: "APP-006",
    name: "UV Hat Wide Brim",
    category: "Apparel",
    categorySlug: "apparel",
    subcategory: "Hats",
    price: 28.0,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/apparel/APP-006-black-studio.png",
  },
  {
    sku: "BCH-008",
    name: "After-Sun Aloe Gel",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Sun Care",
    price: 13.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/beach-essentials/BCH-008-studio.png",
  },
  {
    sku: "BCH-002",
    name: "Beach Ball Inflatable",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Kids",
    price: 6.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-002-studio.png",
  },
  {
    sku: "BCH-003",
    name: "Beach Towel Tropical Print",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Towels",
    price: 24.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-003-palm-print-studio.png",
  },
  {
    sku: "BCH-005",
    name: "Beach Umbrella 7ft",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Shade",
    price: 54.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-005-studio.png",
  },
  {
    sku: "BCH-012",
    name: "Cooler Bag Insulated 24L",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Coolers",
    price: 44.0,
    priceIsFrom: true,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-012-blue-studio.png",
  },
  {
    sku: "BCH-004",
    name: "Microfiber Quick-Dry Towel",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Towels",
    price: 28.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-004-black-studio.png",
  },
  {
    sku: "BCH-009",
    name: "Polarized Sunglasses",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Eyewear",
    price: 39.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/beach-essentials/BCH-009-aviator-black-life.png",
  },
  {
    sku: "BCH-006",
    name: "Pop-Up Beach Tent",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Shade",
    price: 89.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-006-studio.png",
  },
  {
    sku: "BCH-011",
    name: "Reef Walker Water Shoes",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Footwear",
    price: 38.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-011-aqua-life.png",
  },
  {
    sku: "BCH-007",
    name: "Reef-Safe Sunscreen SPF50",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Sun Care",
    price: 19.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/beach-essentials/BCH-007-studio.png",
  },
  {
    sku: "BCH-001",
    name: "Sand Shovel & Bucket Set",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Kids",
    price: 14.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/beach-essentials/BCH-001-studio.png",
  },
  {
    sku: "BCH-010",
    name: "Waterproof Phone Pouch",
    category: "Beach Essentials",
    categorySlug: "beach-essentials",
    subcategory: "Accessories",
    price: 12.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/beach-essentials/BCH-010-studio.png",
  },
  {
    sku: "FSH-008",
    name: "Cast Net 8ft",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Nets",
    price: 45.0,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/fishing/FSH-008-studio.png",
  },
  {
    sku: "FSH-005",
    name: "Live Bait \u2014 Shrimp (lb)",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Bait",
    price: 6.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/fishing/FSH-005-studio.png",
  },
  {
    sku: "FSH-006",
    name: "Live Bait \u2014 Squid (lb)",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Bait",
    price: 7.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/fishing/FSH-006-studio.png",
  },
  {
    sku: "FSH-007",
    name: "Lure Pack Tropical (12pc)",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Tackle",
    price: 22.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/fishing/FSH-007-studio.png",
  },
  {
    sku: "FSH-001",
    name: "Saltwater Spinning Rod 7ft",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Rods",
    price: 98.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/fishing/FSH-001-studio.png",
  },
  {
    sku: "FSH-003",
    name: "Spinning Reel 4000",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Reels",
    price: 84.0,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/fishing/FSH-003-studio.png",
  },
  {
    sku: "FSH-004",
    name: "Tackle Box Deluxe",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Tackle",
    price: 49.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/fishing/FSH-004-studio.png",
  },
  {
    sku: "FSH-002",
    name: "Telescopic Travel Rod",
    category: "Fishing",
    categorySlug: "fishing",
    subcategory: "Rods",
    price: 64.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/fishing/FSH-002-studio.png",
  },
  {
    sku: "WET-001",
    name: "3mm Shorty Wetsuit",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Wetsuits",
    price: 109.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/WET-001-black-life.png",
  },
  {
    sku: "SNK-004",
    name: "Adult Snorkel Set",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Sets",
    price: 64.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/SNK-004-black-studio.png",
  },
  {
    sku: "SNK-005",
    name: "Dry-Top Snorkel",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Snorkels",
    price: 28.5,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/SNK-005-studio.png",
  },
  {
    sku: "SNK-003",
    name: "Junior Snorkel Set (Kids)",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Sets",
    price: 34.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/SNK-003-aqua-studio.png",
  },
  {
    sku: "FIN-003",
    name: "Kids Swim Fins",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Fins",
    price: 29.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/FIN-003-aqua-studio.png",
  },
  {
    sku: "FIN-001",
    name: "Open-Heel Dive Fins",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Fins",
    price: 79.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/FIN-001-black-studio.png",
  },
  {
    sku: "SNK-002",
    name: "Pro Anti-Fog Snorkel Mask",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Masks",
    price: 58.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/SNK-002-black-studio.png",
  },
  {
    sku: "SNK-001",
    name: "Reef Explorer Snorkel Mask",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Masks",
    price: 42.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/SNK-001-black-studio.png",
  },
  {
    sku: "FIN-002",
    name: "Travel Snorkel Fins",
    category: "Snorkel & Dive",
    categorySlug: "snorkel-dive",
    subcategory: "Fins",
    price: 49.99,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/snorkel-dive/FIN-002-black-studio.png",
  },
  {
    sku: "SUR-001",
    name: "7'2 Funboard Surfboard",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Surfboards",
    price: 449.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/surfing/SUR-001-studio.png",
  },
  {
    sku: "SUR-002",
    name: "9'0 Longboard Surfboard",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Surfboards",
    price: 599.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/surfing/SUR-002-studio.png",
  },
  {
    sku: "SUR-003",
    name: "Beginner Foam Surfboard",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Surfboards",
    price: 279.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/surfing/SUR-003-blue-studio.png",
  },
  {
    sku: "KIT-001",
    name: "Beginner Kitesurf Kit",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Kitesurf",
    price: 1099.0,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/surfing/KIT-001-blue-studio.png",
  },
  {
    sku: "KIT-002",
    name: "Kitesurf Harness",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Kitesurf",
    price: 139.0,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/surfing/KIT-002-black-studio.png",
  },
  {
    sku: "SUR-006",
    name: "Skim Board Pro",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Skimboards",
    price: 89.0,
    priceIsFrom: false,
    availability: "Both",
    image: "/images/products/surfing/SUR-006-tropical-studio.png",
  },
  {
    sku: "SUR-004",
    name: "Surf Leash 8ft",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Accessories",
    price: 22.5,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/surfing/SUR-004-black-studio.png",
  },
  {
    sku: "SUR-005",
    name: "Surf Wax Tropical",
    category: "Surfing",
    categorySlug: "surfing",
    subcategory: "Accessories",
    price: 5.99,
    priceIsFrom: false,
    availability: "Sale only",
    image: "/images/products/surfing/SUR-005-studio.png",
  },
];
